from __future__ import annotations


BLS_INTERVIEW_RAW_COLUMNS = [
    "NEWID",
    "CUID",
    "INTERI",
    "QINTRVYR",
    "QINTRVMO",
    "FINLWT21",
    "AGE_REF",
    "FAM_SIZE",
    "BLS_URBN",
    "CUTENURE",
    "REGION",
    "EDUC_REF",
    "HIGH_EDU",
    "PERSLT18",
    "PERSOT64",
    "NO_EARNR",
    "NUM_AUTO",
    "VEHQ",
    "INC_RANK",
    "INCLASS2",
    "FINCBTAX",
    "FSALARYX",
    "INTRDVX",
    "LIQUIDX",
    "CREDITX",
    "STUDNTX",
    "TOTEXPPQ",
    "FOODPQ",
    "FDHOMEPQ",
    "FDAWAYPQ",
    "ALCBEVPQ",
    "HOUSPQ",
    "SHELTPQ",
    "UTILPQ",
    "HOUSEQPQ",
    "APPARPQ",
    "TRANSPQ",
    "GASMOPQ",
    "VEHFINPQ",
    "PUBTRAPQ",
    "HEALTHPQ",
    "ENTERTPQ",
    "PERSCAPQ",
    "READPQ",
    "EDUCAPQ",
    "TOBACCPQ",
    "MISCPQ",
    "CASHCOPQ",
    "PERINSPQ",
    "RETPENPQ",
]


BLS_INTERVIEW_RENAME_MAP = {
    "NEWID": "newid",
    "CUID": "panel_id",
    "INTERI": "interview_number",
    "QINTRVYR": "interview_year",
    "QINTRVMO": "interview_month",
    "FINLWT21": "sample_weight",
    "AGE_REF": "age_ref",
    "FAM_SIZE": "family_size",
    "BLS_URBN": "urban_flag",
    "CUTENURE": "housing_tenure_code",
    "REGION": "region_code",
    "EDUC_REF": "education_ref_code",
    "HIGH_EDU": "highest_education_code",
    "PERSLT18": "children_count",
    "PERSOT64": "older_adults_count",
    "NO_EARNR": "earners_count",
    "NUM_AUTO": "autos_count",
    "VEHQ": "vehicles_count",
    "INC_RANK": "income_rank",
    "INCLASS2": "income_class_code",
    "FINCBTAX": "after_tax_income_annual",
    "FSALARYX": "salary_income_annual",
    "INTRDVX": "interest_dividend_income_annual",
    "LIQUIDX": "liquid_assets",
    "CREDITX": "consumer_credit_balance",
    "STUDNTX": "student_loan_balance",
    "TOTEXPPQ": "total_expenditure_q",
    "FOODPQ": "food_expenditure_q",
    "FDHOMEPQ": "food_home_q",
    "FDAWAYPQ": "food_away_q",
    "ALCBEVPQ": "alcohol_beverages_q",
    "HOUSPQ": "housing_expenditure_q",
    "SHELTPQ": "shelter_expenditure_q",
    "UTILPQ": "utilities_expenditure_q",
    "HOUSEQPQ": "household_equipment_q",
    "APPARPQ": "apparel_expenditure_q",
    "TRANSPQ": "transportation_expenditure_q",
    "GASMOPQ": "gasoline_q",
    "VEHFINPQ": "vehicle_finance_q",
    "PUBTRAPQ": "public_transport_q",
    "HEALTHPQ": "healthcare_expenditure_q",
    "ENTERTPQ": "entertainment_expenditure_q",
    "PERSCAPQ": "personal_care_q",
    "READPQ": "reading_q",
    "EDUCAPQ": "education_expenditure_q",
    "TOBACCPQ": "tobacco_expenditure_q",
    "MISCPQ": "misc_expenditure_q",
    "CASHCOPQ": "cash_contributions_q",
    "PERINSPQ": "personal_insurance_q",
    "RETPENPQ": "retirement_pension_q",
}


BLS_SEQUENCE_BASE_FEATURES = [
    "quarter_index",
    "interview_number",
    "total_expenditure_q",
    "food_expenditure_q",
    "food_home_q",
    "food_away_q",
    "alcohol_beverages_q",
    "housing_expenditure_q",
    "shelter_expenditure_q",
    "utilities_expenditure_q",
    "household_equipment_q",
    "apparel_expenditure_q",
    "transportation_expenditure_q",
    "gasoline_q",
    "vehicle_finance_q",
    "public_transport_q",
    "healthcare_expenditure_q",
    "entertainment_expenditure_q",
    "personal_care_q",
    "reading_q",
    "education_expenditure_q",
    "tobacco_expenditure_q",
    "misc_expenditure_q",
    "cash_contributions_q",
    "personal_insurance_q",
    "retirement_pension_q",
    "family_size",
    "age_ref",
    "earners_count",
    "children_count",
    "older_adults_count",
    "autos_count",
    "vehicles_count",
    "income_rank",
    "after_tax_income_annual",
    "salary_income_annual",
    "interest_dividend_income_annual",
    "liquid_assets",
    "consumer_credit_balance",
    "student_loan_balance",
    "quarterly_income_proxy",
    "essential_spend_q",
    "discretionary_spend_q",
    "spend_to_income_proxy_q",
    "food_away_share",
    "housing_share",
    "transport_share",
    "entertainment_share",
    "urban_flag",
    "housing_tenure_code",
    "region_code",
    "education_ref_code",
    "highest_education_code",
    "income_class_code",
    "young_adult_proxy",
    "student_debt_proxy",
]


def quarter_index(year: int, month: int) -> int:
    return int(year) * 4 + ((int(month) - 1) // 3)
